apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-api-smoke
  namespace: k6-test
  labels:
    workload: k6-runner
    test.tool: k6
spec:
  parallelism: 2
  script:
    configMap:
      name: k6-api-script
      file: event_api_load.js
  runner:
    image: grafana/k6:1.7.1
    metadata:
      labels:
        workload: k6-runner
        test.tool: k6
    envFrom:
      - configMapRef:
          name: k6-runtime-config
      - secretRef:
          name: k6-runtime-secret
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
