apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-api-smoke
  namespace: k6-test
spec:
  parallelism: 2
  script:
    configMap:
      name: k6-api-script
      file: event_api_load.js
  runner:
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi

