name: ngrinder

services:
  controller:
    image: ngrinder/controller:3.5.9-p1
    hostname: controller
    restart: unless-stopped
    ports:
      - "8080:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./volumes/controller:/opt/ngrinder-controller
    networks:
      - ngrinder

  agent:
    image: ngrinder/agent:3.5.9-p1
    restart: unless-stopped
    depends_on:
      - controller
    networks:
      - ngrinder

networks:
  ngrinder:
    driver: bridge
